views.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from .models import User, inventory
from . import db
import re

views = Blueprint('views', __name__)

def removescripts(words):
  cleantextcompile = re.compile('<.*?>')
  cleantext = re.sub(cleantextcompile, '', words)
  return cleantext
  
@views.route('/')
def index():
    return render_template('index.html')

@views.route('/login')
def login():
    return render_template('login.html')

@views.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    if not user:
        flash('Please check your login details and try again.')
        return redirect(url_for('views.login'))
    elif user and not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('views.login'))


    login_user(user, remember=remember)

    return redirect(url_for('views.profile'))

@views.route('/signup')
def signup():
    return render_template('signup.html')

@views.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    user = User.query.filter_by(email=email).first()

    if user:
        flash('Email address already exists.')
        return redirect(url_for('views.signup'))

    new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'))

    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('views.login'))

@views.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.index'))

@views.route('/profile')
@login_required
def profile():
    user = current_user
    items = inventory.query.filter_by(seller_id=user.id)
    return render_template('profile.html', name=user.name, items = items)

@views.route('/inventorypage')
def inventorypage():
    items = inventory.query.all()
    print(items)
    return render_template('inventory.html', items = items)

@views.route('/inventorycreate')
@login_required
def inventorycreatepage():
    return render_template('createinventory.html')

@views.route('/inventorycreate', methods=["POST"])
@login_required
def inventorycreate():
    item = request.form.get('name')
    price = request.form.get('price')
    item = removescripts(item)
    user = current_user
    inventoryitem = inventory(name=item, price=price, seller_id=user.id)
    db.session.add(inventoryitem)
    db.session.commit()
    return redirect(url_for('views.inventorypage'))

@views.route('/updateitems/<int:nid>', methods=['POST','GET'])
@login_required
def updateitems(nid):
    user = current_user
    item_update = inventory.query.get_or_404(nid)
    item_name = item_update.name
    if request.method == "POST":
        newname = request.form['name']
        newname = removescripts(newname)
        item_update.name = newname
        item_update.price = request.form['price']
        if (item_update.seller_id==current_user.id):
            db.session.commit()
            flash('Succesfully Updates ' + item_name)
            return redirect(url_for('views.profile'))
        else:
            flash('Unable to update ' + item_name)
            return redirect(url_for('views.profile'))
    else:
        return render_template('updateinventory.html', items = item_update)

@views.route('/delete/<int:nid>')
@login_required
def deleteitems(nid):
    print(nid)
    user = current_user
    item_delete = inventory.query.get_or_404(nid)
    print(item_delete)
    item_name = item_delete.name
    if(item_delete.seller_id==current_user.id):
        db.session.delete(item_delete)
        db.session.commit()
        flash('Succesfully Deleted ' + item_name)
        return redirect(url_for('views.profile'))
    else:
        flash('UnSuccesful')
        return redirect(url_for('views.profile'))

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
</head>

<body>
  <div class="container">
    <header class="d-flex justify-content-center py-3">
    <ul class="nav nav-pills">
      <li class="nav-item"><a href="{{ url_for('views.index') }}" class="nav-link">
          Home
      </a></li>
      {% if current_user.is_authenticated %}
      <li class="nav-item"><a href="{{ url_for('views.profile') }}" class="nav-link">
          Profile
      </a></li>
      <li class="nav-item"><a href="{{ url_for('views.inventorycreatepage') }}" class="nav-link">
          Create Inventory
      </a></li>
      {% endif %}
      <li class="nav-item"><a href="{{ url_for('views.inventorypage') }}" class="nav-link">
          Inventory
      </a></li>
      {% if not current_user.is_authenticated %}
      <li class="nav-item"><a href="{{ url_for('views.login') }}" class="nav-link">
          Login
      </a></li>
      <li class="nav-item"><a href="{{ url_for('views.signup') }}" class="nav-link">
          Sign Up
      </a></li>

      {% endif %}
      {% if current_user.is_authenticated %}
      <li class="nav-item"><a href="{{ url_for('views.logout') }}" class="nav-link">
          Logout
      </a></li>
      {% endif %}
    </ul>
  </header>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

<script src="{{url_for('static', filename='scriptnew.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>

</html>

templates/createinventory.html
{% extends "base.html" %}

{% block content %}
<main class="form-signin">
  {% with messages = get_flashed_messages() %}
  {% if messages %}
      <div class="notification is-danger">
          {{ messages[0] }} Go to <a href="{{ url_for('views.login') }}">login page</a>.
      </div>
  {% endif %}
  {% endwith %}
  <form action="/inventorycreate" method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <h1 class="h3 mb-3 fw-normal">Item Creation Menu</h1>
    <div class="form-floating">
      <input class="form-control" id="floatingInput" type="text" name="name" placeholder="Name" autofocus="">
      <label for="floatingInput">Name</label>
    </div>
    <div class="form-floating">
      <input class="form-control" id="floatingInput" type="number" name="price" placeholder="Price">
      <label for="floatingPassword">Price</label>
    </div>

    <button class="button is-block is-info is-large is-fullwidth" type="submit">Submit</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
  </form>
</main>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Inventory Management
</h1>
<h2 class="subtitle">
  Welcome to inventory management App
</h2>
{% endblock %}

templates/inventory.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
Inventory
</h1>
<ol class="list-group list-group-numbered">
{% for item in items %}
<li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
      <div class="fw-bold">{{item.name}} - £{{item.price}}</div>
    </div>
  </li>
{% endfor %}
</ol>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
<main class="form-signin">
  {% with messages = get_flashed_messages() %}
  {% if messages %}
      <div class="notification is-danger">
          {{ messages[0] }}
      </div>
  {% endif %}
  {% endwith %}
  <form method="POST" action="/login">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <img class="mb-4" src="../assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input class="form-control" id="floatingInput" type="email" name="email" placeholder="Your Email" autofocus="">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input class="form-control" id="floatingPassword" type="password" name="password" placeholder="Your Password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="button is-block is-info is-large is-fullwidth" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
  </form>
</main>
{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
Welcome, {{ name }}!!!
</h1>
{% with messages = get_flashed_messages() %}
{% if messages %}
    <div class="notification is-danger">
        {{ messages[0] }}
    </div>
{% endif %}
{% endwith %}
<ol class="list-group list-group-numbered">
{% for item in items %}
<li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
      <div class="fw-bold">{{item.name}} - £{{item.price}} </div>
    </div>

    <a class="btn btn-outline-info" href="/updateitems/{{item.id}}">Update</a>
    <a class="btn btn-outline-danger" href="/delete/{{item.id}}">Delete</a>
  </li>
{% endfor %}
</ol>
{% endblock %}

templates/signup.html
{% extends "base.html" %}

{% block content %}
<main class="form-signin">
  {% with messages = get_flashed_messages() %}
  {% if messages %}
      <div class="notification is-danger">
          {{ messages[0] }} Go to <a href="{{ url_for('views.login') }}">login page</a>.
      </div>
  {% endif %}
  {% endwith %}
  <form action="/signup" method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <h1 class="h3 mb-3 fw-normal">Please sign up</h1>

    <div class="form-floating">
      <input class="form-control" id="floatingInput" type="email" name="email" placeholder="Your Email" autofocus="">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input class="form-control" id="floatingInput" type="text" name="name" placeholder="Your Name" autofocus="">
      <label for="floatingInput">Name</label>
    </div>
    <div class="form-floating">
      <input class="form-control" id="floatingPassword" type="password" name="password" placeholder="Your Password">
      <label for="floatingPassword">Password</label>
    </div>

    <button class="button is-block is-info is-large is-fullwidth" type="submit">Sign up</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
  </form>
</main>
{% endblock %}

templates/updateinventory.html
{% extends "base.html" %}

{% block content %}
<main class="form-signin">
  <form action="/updateitems/{{items.id}}" method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <h1 class="h3 mb-3 fw-normal">Update Menu</h1>
    <div class="form-floating">
      <input class="form-control" id="floatingInput" type="text" name="name" value="{{items.name}}" placeholder="Name" autofocus="">
      <label for="floatingInput">Name</label>
    </div>
    <div class="form-floating">
      <input class="form-control" id="floatingInput" type="number" name="price" value="{{items.price}}" placeholder="Price">
      <label for="floatingPassword">Price</label>
    </div>

    <button class="button is-block is-info is-large is-fullwidth" type="submit">Submit</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
  </form>
</main>
{% endblock %}